spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

server:
  ssl:
    key-store-password: U832zeBY
    key-store-type: PKCS12
    key-store: classpath:keystore/local.p12
    key-alias: local
    enabled: true
  port: 8443